[package]
name = "sn_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.27.2"
egui_extras = "0.27.2"
sn_ssh = { path = "../sn_ssh" }
ssh2 = "0.9.4"
