[package]
name = "server_nav_bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.27.2"
server_nav_gui = { path = "../server_nav_gui" }
